num1=input("enter fisrt number")
num2=input("enter second number")
num3=input("enter third number")
# num1,num2,num3=input("enter three number comma seprated").split(",")
print(f"average of three number is : {(int(num1)+int(num2)+int(num3))/3}")